server:
    port: 8080
    context-path: /
spring:
    thymeleaf:
      cache: false
    datasource:
        url: jdbc:mysql://localhost:3306/Kafka_db?autoReconnect=true&useUnicode=true&connectTimeout=1000&socketTimeout=3000&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&readOnlyPropagatesToServer=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        hikari:
          idle-timeout: 10000
    session:
        store-type: none